name: Environment-Based Deployment

on:
  push:
    branches:
      - main
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      STAGING_API_URL: https://staging-api.example.com
      PRODUCTION_API_URL: https://api.example.com
      VERSION: v1.1.0

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Determine Deployment Environment
        id: set-env
        run: |
          echo "Current branch: ${{ github.ref_name }}"
          if [ "${{ github.ref_name }}" = "main" ]; then
            echo "DEPLOYMENT_ENV=production" >> $GITHUB_ENV
            echo "TARGET_API_URL=$PRODUCTION_API_URL" >> $GITHUB_ENV
          else
            echo "DEPLOYMENT_ENV=staging" >> $GITHUB_ENV
            echo "TARGET_API_URL=$STAGING_API_URL" >> $GITHUB_ENV

      - name: Confirm Deployment Configuration
        run: |
          echo "Deployment Environment: $DEPLOYMENT_ENV"
          echo "Target API URL: $TARGET_API_URL"
          echo "Version: $VERSION"

      - name: Deploy Application
        run: |
          if [ "$DEPLOYMENT_ENV" = "production" ]; then
            echo "Deploying to Production Environment"
            # Add actual deployment commands for production here
          else
            echo "Deploying to Staging Environment"
            # Add actual deployment commands for staging here
